// src/courses.js — every golf course and pitch & putt we know of in BC
//
// The app uses this list on the Courses page and to suggest course names
// when someone hosts a game. People can still type any course name.
//
// Each line is one course:
//   name   the course's name, as golfers know it
//   city   the town it's in
//   area   one of the nine areas the app uses (spelled exactly as below)
//   types  what you can play there: "18" (18 holes), "9" (9 holes), "pnp" (pitch & putt or par 3)
//   access "members" for private clubs (members and their guests only). Leave it out otherwise.
//   note   a short caution shown on the Courses page, like a closure. Leave it out otherwise.
//
// To add a course, copy a line and change the details. To remove one, delete its line.
//
// Areas: "Metro Vancouver", "Fraser Valley", "Sea to Sky and Sunshine Coast",
// "Victoria and South Island", "Central and North Island", "Okanagan",
// "Thompson and Cariboo", "Kootenays", "Northern BC"
//
// Last checked: September 2026.

export const COURSES = [

  // ---------- Metro Vancouver (66) ----------
  { name: "Bowen Island Golf Club", city: "Bowen Island", area: "Metro Vancouver", types: ["9"] },
  { name: "Burnaby Mountain Golf Course", city: "Burnaby", area: "Metro Vancouver", types: ["18"] },
  { name: "Central Park Pitch & Putt", city: "Burnaby", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Kensington Pitch & Putt", city: "Burnaby", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Riverway Golf Course", city: "Burnaby", area: "Metro Vancouver", types: ["18"] },
  { name: "Eaglequest Golf Coquitlam", city: "Coquitlam", area: "Metro Vancouver", types: ["pnp"] },
  { name: "GreenTee Country Club Westwood Plateau", city: "Coquitlam", area: "Metro Vancouver", types: ["18", "9"] },
  { name: "Vancouver Golf Club", city: "Coquitlam", area: "Metro Vancouver", types: ["18"], access: "members" },
  { name: "Beach Grove Golf Club", city: "Delta", area: "Metro Vancouver", types: ["18"], access: "members" },
  { name: "Delta Golf & Country Club", city: "Delta", area: "Metro Vancouver", types: ["18"] },
  { name: "Kings Links by the Sea", city: "Delta", area: "Metro Vancouver", types: ["18"] },
  { name: "The Links at Hampton Cove", city: "Delta", area: "Metro Vancouver", types: ["9"], note: "Open March to November" },
  { name: "Sunshine Woods Golf Centre", city: "Delta", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Tsawwassen Springs Golf Course", city: "Delta", area: "Metro Vancouver", types: ["18"] },
  { name: "Belmont Golf Course", city: "Langley", area: "Metro Vancouver", types: ["18"] },
  { name: "Fort Langley Golf Course", city: "Langley", area: "Metro Vancouver", types: ["18"] },
  { name: "GreenTee Country Club Langley", city: "Langley", area: "Metro Vancouver", types: ["18"] },
  { name: "Langley Golf Centre", city: "Langley", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Newlands Golf & Country Club", city: "Langley", area: "Metro Vancouver", types: ["18", "9"] },
  { name: "Poppy Estate Golf Course", city: "Langley", area: "Metro Vancouver", types: ["18"] },
  { name: "Redwoods Golf Course", city: "Langley", area: "Metro Vancouver", types: ["18"] },
  { name: "Tall Timber Golf Course", city: "Langley", area: "Metro Vancouver", types: ["18"] },
  { name: "Hacker's Haven Par 3 Golf Course", city: "Maple Ridge", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Maple Ridge Golf Course", city: "Maple Ridge", area: "Metro Vancouver", types: ["9"] },
  { name: "Murdo Frazer Par 3 Golf Course", city: "North Vancouver", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Northlands Golf Course", city: "North Vancouver", area: "Metro Vancouver", types: ["18"] },
  { name: "Seymour Golf & Country Club", city: "North Vancouver", area: "Metro Vancouver", types: ["18"], note: "Public tee times on Mondays only" },
  { name: "Golden Eagle Golf Club", city: "Pitt Meadows", area: "Metro Vancouver", types: ["18"] },
  { name: "Meadow Gardens Golf Club", city: "Pitt Meadows", area: "Metro Vancouver", types: ["18"] },
  { name: "Pitt Meadows Golf Club", city: "Pitt Meadows", area: "Metro Vancouver", types: ["18"] },
  { name: "Swaneset Bay Resort & Country Club", city: "Pitt Meadows", area: "Metro Vancouver", types: ["18"] },
  { name: "Carnoustie Golf Club", city: "Port Coquitlam", area: "Metro Vancouver", types: ["18"] },
  { name: "Country Meadows Golf Course", city: "Richmond", area: "Metro Vancouver", types: ["18"] },
  { name: "Greenacres Golf Course", city: "Richmond", area: "Metro Vancouver", types: ["18"] },
  { name: "Mayfair Lakes Golf & Country Club", city: "Richmond", area: "Metro Vancouver", types: ["18"] },
  { name: "Mylora Golf Course", city: "Richmond", area: "Metro Vancouver", types: ["18"] },
  { name: "Quilchena Golf & Country Club", city: "Richmond", area: "Metro Vancouver", types: ["18"], access: "members" },
  { name: "Richmond Country Club", city: "Richmond", area: "Metro Vancouver", types: ["18"], access: "members" },
  { name: "Savage Creek Golf Course", city: "Richmond", area: "Metro Vancouver", types: ["18"] },
  { name: "West Richmond Pitch & Putt", city: "Richmond", area: "Metro Vancouver", types: ["pnp"], note: "Open May to Thanksgiving" },
  { name: "Birdies & Buckets Family Golf Centre", city: "Surrey", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Clayton Hills Golf Course", city: "Surrey", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Guildford Golf & Country Club", city: "Surrey", area: "Metro Vancouver", types: ["18"] },
  { name: "Hazelmere Golf & Tennis Club", city: "Surrey", area: "Metro Vancouver", types: ["18"] },
  { name: "The Hills at Portal Golf Club", city: "Surrey", area: "Metro Vancouver", types: ["18"] },
  { name: "Meridian Hills Golf & Wine Club", city: "Surrey", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Morgan Creek Golf Course", city: "Surrey", area: "Metro Vancouver", types: ["18"] },
  { name: "Nico Wynd Golf Club", city: "Surrey", area: "Metro Vancouver", types: ["9"] },
  { name: "Northview Golf & Country Club", city: "Surrey", area: "Metro Vancouver", types: ["18"] },
  { name: "Peace Portal Par 3", city: "Surrey", area: "Metro Vancouver", types: ["pnp"], note: "Call ahead to confirm it's open" },
  { name: "Surrey Golf Club", city: "Surrey", area: "Metro Vancouver", types: ["18", "9"] },
  { name: "Westfield Country Club", city: "Surrey", area: "Metro Vancouver", types: ["9"] },
  { name: "Fraserview Golf Course", city: "Vancouver", area: "Metro Vancouver", types: ["18"] },
  { name: "Langara Golf Course", city: "Vancouver", area: "Metro Vancouver", types: ["18"] },
  { name: "Marine Drive Golf Club", city: "Vancouver", area: "Metro Vancouver", types: ["18"], access: "members" },
  { name: "McCleery Golf Course", city: "Vancouver", area: "Metro Vancouver", types: ["18"] },
  { name: "Musqueam Golf & Learning Academy", city: "Vancouver", area: "Metro Vancouver", types: ["18"] },
  { name: "Point Grey Golf & Country Club", city: "Vancouver", area: "Metro Vancouver", types: ["18"], access: "members" },
  { name: "Queen Elizabeth Park Pitch & Putt", city: "Vancouver", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Rupert Park Pitch & Putt", city: "Vancouver", area: "Metro Vancouver", types: ["pnp"] },
  { name: "Shaughnessy Golf & Country Club", city: "Vancouver", area: "Metro Vancouver", types: ["18"], access: "members" },
  { name: "Stanley Park Pitch & Putt", city: "Vancouver", area: "Metro Vancouver", types: ["pnp"] },
  { name: "University Golf Club", city: "Vancouver", area: "Metro Vancouver", types: ["18"] },
  { name: "Ambleside Par 3 Golf Course", city: "West Vancouver", area: "Metro Vancouver", types: ["pnp"], note: "Open March to October" },
  { name: "Capilano Golf & Country Club", city: "West Vancouver", area: "Metro Vancouver", types: ["18"], access: "members" },
  { name: "Gleneagles Golf Course", city: "West Vancouver", area: "Metro Vancouver", types: ["9"] },

  // ---------- Fraser Valley (17) ----------
  { name: "Fraserglen Golf Course", city: "Abbotsford", area: "Fraser Valley", types: ["18"] },
  { name: "Ledgeview Golf Club", city: "Abbotsford", area: "Fraser Valley", types: ["18"] },
  { name: "Valley Golf Centre", city: "Abbotsford", area: "Fraser Valley", types: ["9"] },
  { name: "Cheam Mountain Golf Course", city: "Chilliwack", area: "Fraser Valley", types: ["pnp"] },
  { name: "Chilliwack Golf Club", city: "Chilliwack", area: "Fraser Valley", types: ["18"] },
  { name: "The Falls Golf Club", city: "Chilliwack", area: "Fraser Valley", types: ["18"] },
  { name: "Kinkora Golf Course", city: "Chilliwack", area: "Fraser Valley", types: ["pnp"] },
  { name: "Meadowlands Golf & Country Club", city: "Chilliwack", area: "Fraser Valley", types: ["18"] },
  { name: "Royalwood Golf Course", city: "Chilliwack", area: "Fraser Valley", types: ["18"] },
  { name: "Cultus Lake Golf Club", city: "Cultus Lake", area: "Fraser Valley", types: ["18"] },
  { name: "Harrison Resort Golf Course", city: "Harrison Hot Springs", area: "Fraser Valley", types: ["9"] },
  { name: "Sandpiper Golf Club", city: "Harrison Mills", area: "Fraser Valley", types: ["18"] },
  { name: "Hope Golf & Country Club", city: "Hope", area: "Fraser Valley", types: ["18"] },
  { name: "Cedar Ridge Golf Course", city: "Mission", area: "Fraser Valley", types: ["pnp"] },
  { name: "Eighteen Pastures Golf Course", city: "Mission", area: "Fraser Valley", types: ["18"] },
  { name: "Mission Golf & Country Club", city: "Mission", area: "Fraser Valley", types: ["18"] },
  { name: "Bridal Falls Golf Club", city: "Rosedale", area: "Fraser Valley", types: ["9"] },

  // ---------- Sea to Sky and Sunshine Coast (12) ----------
  { name: "Furry Creek Golf & Country Club", city: "Furry Creek", area: "Sea to Sky and Sunshine Coast", types: ["18"] },
  { name: "Langdale Heights RV & Par 3 Golf Resort", city: "Gibsons", area: "Sea to Sky and Sunshine Coast", types: ["pnp"], note: "Call ahead to confirm it's open" },
  { name: "Pender Harbour Golf Club", city: "Madeira Park", area: "Sea to Sky and Sunshine Coast", types: ["9"] },
  { name: "Big Sky Golf Club", city: "Pemberton", area: "Sea to Sky and Sunshine Coast", types: ["18"] },
  { name: "Sunstone Golf Club", city: "Pemberton", area: "Sea to Sky and Sunshine Coast", types: ["18"] },
  { name: "Myrtle Point Golf Club", city: "Powell River", area: "Sea to Sky and Sunshine Coast", types: ["18"] },
  { name: "Sunshine Coast Golf & Country Club", city: "Roberts Creek", area: "Sea to Sky and Sunshine Coast", types: ["18"] },
  { name: "Blue Ocean Golf Club", city: "Sechelt", area: "Sea to Sky and Sunshine Coast", types: ["18"] },
  { name: "Squamish Valley Golf Club", city: "Squamish", area: "Sea to Sky and Sunshine Coast", types: ["18"] },
  { name: "Fairmont Chateau Whistler Golf Club", city: "Whistler", area: "Sea to Sky and Sunshine Coast", types: ["18"] },
  { name: "Nicklaus North Golf Course", city: "Whistler", area: "Sea to Sky and Sunshine Coast", types: ["18"] },
  { name: "Whistler Golf Club", city: "Whistler", area: "Sea to Sky and Sunshine Coast", types: ["18"], note: "Closed for renovation until summer 2027" },

  // ---------- Victoria and South Island (26) ----------
  { name: "Mount Brenton Golf Course", city: "Chemainus", area: "Victoria and South Island", types: ["18"] },
  { name: "Arbutus Ridge Golf Club", city: "Cobble Hill", area: "Victoria and South Island", types: ["18"] },
  { name: "Juan de Fuca Golf Course", city: "Colwood", area: "Victoria and South Island", types: ["pnp"] },
  { name: "Olympic View Golf Club", city: "Colwood", area: "Victoria and South Island", types: ["18"] },
  { name: "Royal Colwood Golf Club", city: "Colwood", area: "Victoria and South Island", types: ["18"], access: "members" },
  { name: "Cowichan Golf Club", city: "Duncan", area: "Victoria and South Island", types: ["18"] },
  { name: "Duncan Meadows Golf Course", city: "Duncan", area: "Victoria and South Island", types: ["18"] },
  { name: "Gorge Vale Golf Club", city: "Esquimalt", area: "Victoria and South Island", types: ["18"], access: "members" },
  { name: "Galiano Golf Course", city: "Galiano Island", area: "Victoria and South Island", types: ["9"] },
  { name: "March Meadows Golf Club", city: "Honeymoon Bay", area: "Victoria and South Island", types: ["9"] },
  { name: "Ladysmith Golf Club", city: "Ladysmith", area: "Victoria and South Island", types: ["pnp"] },
  { name: "Bear Mountain (Mountain Course)", city: "Langford", area: "Victoria and South Island", types: ["18"] },
  { name: "Bear Mountain (Valley Course)", city: "Langford", area: "Victoria and South Island", types: ["18"] },
  { name: "Metchosin Golf Course", city: "Metchosin", area: "Victoria and South Island", types: ["9"] },
  { name: "Victoria Golf Centre", city: "Metchosin", area: "Victoria and South Island", types: ["pnp"] },
  { name: "Ardmore Golf Course", city: "North Saanich", area: "Victoria and South Island", types: ["9"] },
  { name: "Henderson Park Par-3 Golf Course", city: "Oak Bay", area: "Victoria and South Island", types: ["pnp"], note: "Open mid-March to mid-November" },
  { name: "Uplands Golf Club", city: "Oak Bay", area: "Victoria and South Island", types: ["18"] },
  { name: "Victoria Golf Club", city: "Oak Bay", area: "Victoria and South Island", types: ["18"], access: "members" },
  { name: "Pender Island Golf & Country Club", city: "Pender Island", area: "Victoria and South Island", types: ["9"] },
  { name: "Cedar Hill Golf Course", city: "Saanich", area: "Victoria and South Island", types: ["18"] },
  { name: "Cordova Bay Golf Course", city: "Saanich", area: "Victoria and South Island", types: ["18", "pnp"] },
  { name: "Highland Pacific Golf", city: "Saanich", area: "Victoria and South Island", types: ["18"] },
  { name: "Mount Douglas Golf Course", city: "Saanich", area: "Victoria and South Island", types: ["9"] },
  { name: "Salt Spring Island Golf Club", city: "Salt Spring Island", area: "Victoria and South Island", types: ["9"] },
  { name: "DeMamiel Creek Golf Course", city: "Sooke", area: "Victoria and South Island", types: ["pnp"], note: "Open late March to October" },

  // ---------- Central and North Island (29) ----------
  { name: "Saratoga Beach Golf Club", city: "Black Creek", area: "Central and North Island", types: ["9"] },
  { name: "Campbell River Golf Club", city: "Campbell River", area: "Central and North Island", types: ["18"] },
  { name: "Storey Creek Golf Club", city: "Campbell River", area: "Central and North Island", types: ["18"] },
  { name: "Comox Golf Club", city: "Comox", area: "Central and North Island", types: ["9"] },
  { name: "Glacier Greens Golf Club", city: "Comox", area: "Central and North Island", types: ["18"] },
  { name: "The Park at Crown Isle", city: "Comox", area: "Central and North Island", types: ["pnp"] },
  { name: "Crown Isle Resort & Golf Community", city: "Courtenay", area: "Central and North Island", types: ["18"] },
  { name: "Mulligans Golf Course", city: "Courtenay", area: "Central and North Island", types: ["pnp"] },
  { name: "Sunnydale Golf & Country Club", city: "Courtenay", area: "Central and North Island", types: ["18"] },
  { name: "Gabriola Golf & Country Club", city: "Gabriola Island", area: "Central and North Island", types: ["9"] },
  { name: "Gold River Golf Club", city: "Gold River", area: "Central and North Island", types: ["9"] },
  { name: "Winchelsea View Golf Course", city: "Lantzville", area: "Central and North Island", types: ["18"] },
  { name: "Beban Park Golf Course", city: "Nanaimo", area: "Central and North Island", types: ["pnp"] },
  { name: "Cottonwood Golf Course", city: "Nanaimo", area: "Central and North Island", types: ["18"] },
  { name: "Eaglequest Nanaimo (Fiddlers Green)", city: "Nanaimo", area: "Central and North Island", types: ["pnp"] },
  { name: "Nanaimo Golf Club", city: "Nanaimo", area: "Central and North Island", types: ["18"] },
  { name: "Pryde Vista Golf Course", city: "Nanaimo", area: "Central and North Island", types: ["9"] },
  { name: "Fairwinds Golf Club", city: "Nanoose Bay", area: "Central and North Island", types: ["18"] },
  { name: "Brigadoon Golf Course", city: "Parksville", area: "Central and North Island", types: ["pnp"] },
  { name: "Morningstar Golf Club", city: "Parksville", area: "Central and North Island", types: ["18"] },
  { name: "Alberni Golf Club", city: "Port Alberni", area: "Central and North Island", types: ["18"] },
  { name: "Hollies Executive Golf Course", city: "Port Alberni", area: "Central and North Island", types: ["pnp"] },
  { name: "Seven Hills Golf & Country Club", city: "Port Hardy", area: "Central and North Island", types: ["9"] },
  { name: "Quadra Island Golf Course", city: "Quadra Island", area: "Central and North Island", types: ["9"] },
  { name: "Arrowsmith Golf & Country Club", city: "Qualicum Beach", area: "Central and North Island", types: ["18"] },
  { name: "Eaglecrest Golf Club", city: "Qualicum Beach", area: "Central and North Island", types: ["9"], note: "Closed for rebuild until spring 2027" },
  { name: "Pheasant Glen Golf Resort", city: "Qualicum Beach", area: "Central and North Island", types: ["18"] },
  { name: "Qualicum Beach Memorial Golf Club", city: "Qualicum Beach", area: "Central and North Island", types: ["9"] },
  { name: "Long Beach Golf Course", city: "Tofino", area: "Central and North Island", types: ["9"] },

  // ---------- Okanagan (46) ----------
  { name: "North Shuswap Golf Club", city: "Anglemont", area: "Okanagan", types: ["9"] },
  { name: "The Overlander Golf & Event Center", city: "Armstrong", area: "Okanagan", types: ["9"] },
  { name: "Shuswap Lake Golf Course at Blind Bay", city: "Blind Bay", area: "Okanagan", types: ["18"] },
  { name: "Cherryville RV Golf & Roadhouse Cafe", city: "Cherryville", area: "Okanagan", types: ["9"] },
  { name: "Mabel Lake Golf & Airpark", city: "Enderby", area: "Okanagan", types: ["9"] },
  { name: "Birchdale Golf Course", city: "Grindrod", area: "Okanagan", types: ["9"] },
  { name: "St. Andrews by the Lake Golf Resort", city: "Kaleden", area: "Okanagan", types: ["9"] },
  { name: "Twin Lakes Golf Course & RV Park", city: "Kaleden", area: "Okanagan", types: ["18"] },
  { name: "Black Mountain Golf Club", city: "Kelowna", area: "Okanagan", types: ["18"] },
  { name: "Gallagher's Canyon Golf & Country Club", city: "Kelowna", area: "Okanagan", types: ["18", "9"] },
  { name: "The Harvest Golf Club", city: "Kelowna", area: "Okanagan", types: ["18"] },
  { name: "Kelowna Golf & Country Club", city: "Kelowna", area: "Okanagan", types: ["18"], access: "members" },
  { name: "Kelowna Springs Golf Club", city: "Kelowna", area: "Okanagan", types: ["9"] },
  { name: "Michaelbrook Golf Club", city: "Kelowna", area: "Okanagan", types: ["18"] },
  { name: "Mission Creek Golf Club", city: "Kelowna", area: "Okanagan", types: ["18"] },
  { name: "Okanagan Golf Club", city: "Kelowna", area: "Okanagan", types: ["18"] },
  { name: "Orchard Greens Golf Club", city: "Kelowna", area: "Okanagan", types: ["9"] },
  { name: "Shadow Ridge Golf Club", city: "Kelowna", area: "Okanagan", types: ["18"] },
  { name: "Sunset Ranch Golf & Country Club", city: "Kelowna", area: "Okanagan", types: ["18"] },
  { name: "Tower Ranch Golf Club", city: "Kelowna", area: "Okanagan", types: ["18"] },
  { name: "Coldstream Golf Course", city: "Lumby", area: "Okanagan", types: ["9"] },
  { name: "Lumby Golf Club", city: "Lumby", area: "Okanagan", types: ["9"] },
  { name: "Fairview Mountain Golf Club", city: "Oliver", area: "Okanagan", types: ["18"] },
  { name: "Nk'Mip Canyon Desert Golf Course", city: "Oliver", area: "Okanagan", types: ["18"] },
  { name: "Osoyoos Golf Club", city: "Osoyoos", area: "Okanagan", types: ["18"] },
  { name: "Sonora Dunes Golf Course", city: "Osoyoos", area: "Okanagan", types: ["9"] },
  { name: "Penticton Golf & Country Club", city: "Penticton", area: "Okanagan", types: ["18"] },
  { name: "Pine Hills Golf Club", city: "Penticton", area: "Okanagan", types: ["pnp"] },
  { name: "Skaha Meadows Golf Course", city: "Penticton", area: "Okanagan", types: ["9"] },
  { name: "Wow Golf Club", city: "Penticton", area: "Okanagan", types: ["9"] },
  { name: "Princeton Golf Club", city: "Princeton", area: "Okanagan", types: ["18"] },
  { name: "Club Shuswap Golf & RV", city: "Salmon Arm", area: "Okanagan", types: ["18", "pnp"] },
  { name: "Salmon Arm Golf Club", city: "Salmon Arm", area: "Okanagan", types: ["18", "9"] },
  { name: "Shuswap National Golf Club", city: "Salmon Arm", area: "Okanagan", types: ["18"] },
  { name: "Eagle River Golf & Country Club", city: "Sicamous", area: "Okanagan", types: ["9"] },
  { name: "MaraHills Golf Resort", city: "Sicamous", area: "Okanagan", types: ["18"] },
  { name: "Cedar Heights Community Par 3", city: "Sorrento", area: "Okanagan", types: ["pnp"], note: "Volunteer-run; call ahead" },
  { name: "Sumac Ridge Golf & Country Club", city: "Summerland", area: "Okanagan", types: ["pnp"] },
  { name: "Summerland Golf & Country Club", city: "Summerland", area: "Okanagan", types: ["18"] },
  { name: "Hillview Golf Course", city: "Vernon", area: "Okanagan", types: ["18"] },
  { name: "Predator Ridge Golf Resort", city: "Vernon", area: "Okanagan", types: ["18"] },
  { name: "The Rise Resort", city: "Vernon", area: "Okanagan", types: ["18"] },
  { name: "Spallumcheen Golf & Country Club", city: "Vernon", area: "Okanagan", types: ["18", "9"] },
  { name: "Vernon Golf & Country Club", city: "Vernon", area: "Okanagan", types: ["18"], note: "Members' club; limited public times" },
  { name: "Shannon Lake Golf Club", city: "West Kelowna", area: "Okanagan", types: ["18"] },
  { name: "Two Eagles Golf Course & Academy", city: "West Kelowna", area: "Okanagan", types: ["18"] },

  // ---------- Thompson and Cariboo (26) ----------
  { name: "108 Golf Resort", city: "108 Mile Ranch", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Chinook Cove Golf Club", city: "Barriere", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Semlin Valley Golf Course", city: "Cache Creek", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Sunshore Golf Course", city: "Chase", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Talking Rock Golf Course", city: "Chase", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Civilia Golf Retreat", city: "Clearwater", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Wells Gray Golf & RV Resort", city: "Clearwater", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Bighorn Golf & Country Club", city: "Kamloops", area: "Thompson and Cariboo", types: ["18"] },
  { name: "The Dunes at Kamloops", city: "Kamloops", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Eaglepoint Golf Resort", city: "Kamloops", area: "Thompson and Cariboo", types: ["18"] },
  { name: "GreenTee Country Club Tobiano", city: "Kamloops", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Kamloops Golf & Country Club", city: "Kamloops", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Mt. Paul Golf Course", city: "Kamloops", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Pineridge Golf Course", city: "Kamloops", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Rivershore Golf Links", city: "Kamloops", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Lillooet Sheep Pasture Golf Course", city: "Lillooet", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Meadow Creek Golf Course", city: "Logan Lake", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Merritt Golf & Country Club", city: "Merritt", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Quesnel Golf Club", city: "Quesnel", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Richbar Golf & Gardens", city: "Quesnel", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Quilchena on the Lake Golf Course", city: "Quilchena", area: "Thompson and Cariboo", types: ["9"], note: "Call ahead to confirm it's open" },
  { name: "Sagebrush Golf Club", city: "Quilchena", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Sun Peaks Golf Course", city: "Sun Peaks", area: "Thompson and Cariboo", types: ["18"] },
  { name: "Coyote Rock Golf Course", city: "Williams Lake", area: "Thompson and Cariboo", types: ["9"] },
  { name: "Fireman's Fairway Golf Course", city: "Williams Lake", area: "Thompson and Cariboo", types: ["pnp"] },
  { name: "Williams Lake Golf & Tennis Club", city: "Williams Lake", area: "Thompson and Cariboo", types: ["18"] },

  // ---------- Kootenays (46) ----------
  { name: "Balfour Golf Course", city: "Balfour", area: "Kootenays", types: ["18"] },
  { name: "Castlegar Golf Club", city: "Castlegar", area: "Kootenays", types: ["18"] },
  { name: "Cascade Par 3", city: "Christina Lake", area: "Kootenays", types: ["pnp"] },
  { name: "Christina Lake Golf Club", city: "Christina Lake", area: "Kootenays", types: ["18"] },
  { name: "Cranbrook Golf Club", city: "Cranbrook", area: "Kootenays", types: ["18"] },
  { name: "Mission Hills Golf Course", city: "Cranbrook", area: "Kootenays", types: ["pnp"] },
  { name: "Shadow Mountain Golf Course", city: "Cranbrook", area: "Kootenays", types: ["18"] },
  { name: "St. Eugene Golf Resort", city: "Cranbrook", area: "Kootenays", types: ["18"] },
  { name: "Wildstone Golf Course", city: "Cranbrook", area: "Kootenays", types: ["18"] },
  { name: "Kokanee Springs Golf Resort", city: "Crawford Bay", area: "Kootenays", types: ["18"] },
  { name: "Creston Golf Club", city: "Creston", area: "Kootenays", types: ["18"] },
  { name: "Edgewater Hilltop Par 3", city: "Edgewater", area: "Kootenays", types: ["pnp"] },
  { name: "Mountain Meadows Golf Course", city: "Elkford", area: "Kootenays", types: ["9"] },
  { name: "Coys Par 3", city: "Fairmont Hot Springs", area: "Kootenays", types: ["pnp"] },
  { name: "Fairmont Hot Springs Resort (Creekside Par 3)", city: "Fairmont Hot Springs", area: "Kootenays", types: ["pnp"] },
  { name: "Fairmont Hot Springs Resort (Mountainside)", city: "Fairmont Hot Springs", area: "Kootenays", types: ["18"] },
  { name: "Fairmont Hot Springs Resort (Riverside)", city: "Fairmont Hot Springs", area: "Kootenays", types: ["18"] },
  { name: "Fauquier & District Golf Club", city: "Fauquier", area: "Kootenays", types: ["9"] },
  { name: "Fernie Golf Club", city: "Fernie", area: "Kootenays", types: ["18"] },
  { name: "Champion Lakes Golf & Country Club", city: "Fruitvale", area: "Kootenays", types: ["9"] },
  { name: "Golden Golf Club", city: "Golden", area: "Kootenays", types: ["18"] },
  { name: "Eagle Ranch Golf Resort", city: "Invermere", area: "Kootenays", types: ["18"] },
  { name: "The Point Course at Copper Point", city: "Invermere", area: "Kootenays", types: ["18"] },
  { name: "The Ridge Course at Copper Point", city: "Invermere", area: "Kootenays", types: ["18"] },
  { name: "Will-O-Bend Golf & RV Park", city: "Jaffray", area: "Kootenays", types: ["9"] },
  { name: "Kaslo Golf Club", city: "Kaslo", area: "Kootenays", types: ["9"] },
  { name: "Bootleg Gap Golf", city: "Kimberley", area: "Kootenays", types: ["18", "9"] },
  { name: "Kimberley Golf Club", city: "Kimberley", area: "Kootenays", types: ["18"] },
  { name: "Trickle Creek Golf Resort", city: "Kimberley", area: "Kootenays", types: ["18"] },
  { name: "Nakusp Centennial Golf Club", city: "Nakusp", area: "Kootenays", types: ["9"] },
  { name: "Granite Pointe Golf Club", city: "Nelson", area: "Kootenays", types: ["18"] },
  { name: "Slocan Lake Golf Club", city: "New Denver", area: "Kootenays", types: ["9"] },
  { name: "Greywolf Golf Course", city: "Panorama", area: "Kootenays", types: ["18"] },
  { name: "Radium Golf Group (Radium Course)", city: "Radium Hot Springs", area: "Kootenays", types: ["18"] },
  { name: "Radium Golf Group (Springs Course)", city: "Radium Hot Springs", area: "Kootenays", types: ["18"] },
  { name: "Se-tetkwa Golf Course", city: "Radium Hot Springs", area: "Kootenays", types: ["9"] },
  { name: "Spur Valley Golf Resort", city: "Radium Hot Springs", area: "Kootenays", types: ["9"] },
  { name: "Revelstoke Golf Club", city: "Revelstoke", area: "Kootenays", types: ["18"] },
  { name: "Riondel Golf Club", city: "Riondel", area: "Kootenays", types: ["9"] },
  { name: "Kettle Valley Golf Club", city: "Rock Creek", area: "Kootenays", types: ["9"] },
  { name: "Redstone Resort", city: "Rossland", area: "Kootenays", types: ["18"] },
  { name: "Salmo Golf Club", city: "Salmo", area: "Kootenays", types: ["9"] },
  { name: "Sparwood Golf Club", city: "Sparwood", area: "Kootenays", types: ["9"] },
  { name: "Birchbank Golf Course", city: "Trail", area: "Kootenays", types: ["18"] },
  { name: "Windermere Valley Golf Course", city: "Windermere", area: "Kootenays", types: ["18"] },
  { name: "Valley View Golf Club", city: "Winlaw", area: "Kootenays", types: ["9"] },

  // ---------- Northern BC (26) ----------
  { name: "Carnoustie Golf & Country Club", city: "Burns Lake", area: "Northern BC", types: ["9"] },
  { name: "Natural Springs Golf Resort", city: "Chetwynd", area: "Northern BC", types: ["9"] },
  { name: "Dawson Creek Golf & Country Club", city: "Dawson Creek", area: "Northern BC", types: ["18"] },
  { name: "Farmington Fairways", city: "Dawson Creek", area: "Northern BC", types: ["9"] },
  { name: "Poplar Hills Golf Club", city: "Fort Nelson", area: "Northern BC", types: ["9"] },
  { name: "Stuart Lake Golf Club", city: "Fort St. James", area: "Northern BC", types: ["9"] },
  { name: "Fort St. John Links Golf Course", city: "Fort St. John", area: "Northern BC", types: ["9"] },
  { name: "Lake Point Golf & Country Club", city: "Fort St. John", area: "Northern BC", types: ["18"] },
  { name: "Molyhills Golf Club", city: "Fraser Lake", area: "Northern BC", types: ["9"] },
  { name: "Willow Grove Golf & Country Club", city: "Houston", area: "Northern BC", types: ["9"] },
  { name: "Hirsch Creek Golf & Winter Club", city: "Kitimat", area: "Northern BC", types: ["18"] },
  { name: "Mackenzie Golf & Country Club", city: "Mackenzie", area: "Northern BC", types: ["9"] },
  { name: "Dixon Entrance Golf & Country Club", city: "Masset", area: "Northern BC", types: ["9"] },
  { name: "Aberdeen Glen Golf Club", city: "Prince George", area: "Northern BC", types: ["18"] },
  { name: "Alder Hills Golf Course", city: "Prince George", area: "Northern BC", types: ["pnp"] },
  { name: "Aspen Grove Golf Course", city: "Prince George", area: "Northern BC", types: ["18"] },
  { name: "Pine Valley Golf Centre", city: "Prince George", area: "Northern BC", types: ["pnp"] },
  { name: "Prince George Golf & Curling Club", city: "Prince George", area: "Northern BC", types: ["18"] },
  { name: "Prince Rupert Golf Club", city: "Prince Rupert", area: "Northern BC", types: ["18"] },
  { name: "Willows Golf Course", city: "Sandspit", area: "Northern BC", types: ["9"] },
  { name: "Smithers Golf & Country Club", city: "Smithers", area: "Northern BC", types: ["18"] },
  { name: "Lone Wolf Golf Club", city: "Taylor", area: "Northern BC", types: ["18"] },
  { name: "Skeena Valley Golf & Country Club", city: "Terrace", area: "Northern BC", types: ["18"] },
  { name: "Tumbler Ridge Golf & Country Club", city: "Tumbler Ridge", area: "Northern BC", types: ["9"] },
  { name: "Valemount Pines Golf & RV Park", city: "Valemount", area: "Northern BC", types: ["9"] },
  { name: "Omineca Golf and Country Club", city: "Vanderhoof", area: "Northern BC", types: ["18"] },
];
